import agroImg from "../assets/images/productos/agro/card.jpg";
import apImg from "../assets/images/productos/ap/card.jpg";
import apColoniaImg from "../assets/images/productos/ap/cardcolonia.jpg";
import apMedicinaImg from "../assets/images/productos/ap/cardmedicina.jpg";
import automotorImg from "../assets/images/productos/automotor/automotor.jpg";
import casaImg from "../assets/images/productos/casa/casa.jpg";
import ciclistasImg from "../assets/images/productos/ciclistas/card.jpg";
import clasicoImg from "../assets/images/productos/clasicos/card.jpg";
import incendioImg from "../assets/images/productos/incendio/card.jpg";
import colectivoImg from "../assets/images/productos/colectivo/card.jpg";
import comercioImg from "../assets/images/productos/comercio/card.jpg";
import consorcioImg from "../assets/images/productos/consorcio/card.jpg";
import ecomovilidadImg from "../assets/images/productos/ecomovilidad/card.jpg";
import embarcacionesImg from "../assets/images/productos/embarcaciones/card.jpg";
import foodtruckImg from "../assets/images/productos/foodtruck/card.jpg";
import identidadImg from "../assets/images/productos/identidad/card.jpg";
import operativoImg from "../assets/images/productos/operativo/card.jpg";
import rcProImg from "../assets/images/productos/rcPro/card.jpg";
import retiroImg from "../assets/images/productos/retiro/card.jpg";
import sepelioImg from "../assets/images/productos/sepelio/card.jpg";
import vidaImg from "../assets/images/productos/vida/card.jpg";

import fichaAuto from "../assets/images/productos/automotor/ficha.pdf";
import videoAuto from "../assets/images/productos/automotor/siniestro.mp4";
import videoAuto1 from "../assets/images/productos/automotor/conciencia.mp4";
import videoAuto2 from "../assets/images/productos/automotor/control.mp4";

export const productos = [
  {
    id: 1,
    nombre: "Seguros agropecuarios",
    descripcion: "",
    imagen1: agroImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 2,
    nombre: "Accidentes Personales",
    descripcion: "",
    imagen1: apImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 3,
    nombre: "Accidentes personales para Colonias de vacaciones",
    descripcion: "",
    imagen1: apColoniaImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 4,
    nombre: "Accidentes Personales Medicina",
    descripcion: "",
    imagen1: apMedicinaImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 5,
    nombre: "Seguros automotores",
    descripcion:
      "Nuestros seguros automotores están diseñados para brindar protección integral ante daños, robos, responsabilidad civil y eventos imprevistos. Ofrecemos distintas coberturas adaptadas a cada necesidad, garantizando respaldo económico, asistencia inmediata y tranquilidad en todo momento.",
    imagen1: automotorImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: videoAuto,
    video1: videoAuto1,
    video2: videoAuto2,
    fichaPDF: fichaAuto,
  },
  {
    id: 6,
    nombre: "Combinado Familiar (casa)",
    descripcion: "",
    imagen1: casaImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 7,
    nombre: "Integral Ciclistas",
    descripcion: "",
    imagen1: ciclistasImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 8,
    nombre: "Autos Clásicos",
    descripcion: "",
    imagen1: clasicoImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 9,
    nombre: "Vida Colectivo",
    descripcion: "",
    imagen1: colectivoImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 10,
    nombre: "Integral de Comercio",
    descripcion: "",
    imagen1: comercioImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 11,
    nombre: "Integral de Consorcio",
    descripcion: "",
    imagen1: consorcioImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 12,
    nombre: "EcoMovilidad",
    descripcion: "",
    imagen1: ecomovilidadImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 13,
    nombre: "Embarcaciones",
    descripcion: "",
    imagen1: embarcacionesImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 14,
    nombre: "FoodTruck",
    descripcion: "",
    imagen1: foodtruckImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 15,
    nombre: "Robo de Identidad",
    descripcion: "",
    imagen1: identidadImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 16,
    nombre: "Seguros de incendio",
    descripcion: "",
    imagen1: incendioImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 17,
    nombre: "Todo Riesgo Operativo",
    descripcion: "",
    imagen1: operativoImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 18,
    nombre: "Responsabilidad Civil Profesional",
    descripcion: "",
    imagen1: rcProImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 19,
    nombre: "Seguros de Retiro",
    descripcion: "",
    imagen1: retiroImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 20,
    nombre: "Seguros de Sepelio",
    descripcion: "",
    imagen1: sepelioImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
  {
    id: 21,
    nombre: "Seguros de Vida",
    descripcion: "",
    imagen1: vidaImg,
    imagen2: "",
    imagen3: "",
    imagen4: "",
    video: "",
    video1: "",
    video2: "",
    fichaPDF: "",
  },
];
